# Generated by Django 3.2.5 on 2021-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('create_day', models.DateTimeField(auto_now_add=True)),
                ('modify_day', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
