# Generated by Django 3.2.5 on 2021-08-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
